// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// discretizate_density
List discretizate_density(Function density, NumericVector parameters, double ini_point, double truncation_point, double max_deltat, double max_probability);
RcppExport SEXP _phfrailty_discretizate_density(SEXP densitySEXP, SEXP parametersSEXP, SEXP ini_pointSEXP, SEXP truncation_pointSEXP, SEXP max_deltatSEXP, SEXP max_probabilitySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Function >::type density(densitySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type parameters(parametersSEXP);
    Rcpp::traits::input_parameter< double >::type ini_point(ini_pointSEXP);
    Rcpp::traits::input_parameter< double >::type truncation_point(truncation_pointSEXP);
    Rcpp::traits::input_parameter< double >::type max_deltat(max_deltatSEXP);
    Rcpp::traits::input_parameter< double >::type max_probability(max_probabilitySEXP);
    rcpp_result_gen = Rcpp::wrap(discretizate_density(density, parameters, ini_point, truncation_point, max_deltat, max_probability));
    return rcpp_result_gen;
END_RCPP
}
// discretizate_bivdensity
List discretizate_bivdensity(Function density, NumericVector parameters, double ini_point1, double truncation_point1, double max_deltat1, double ini_point2, double truncation_point2, double max_deltat2, double max_probability);
RcppExport SEXP _phfrailty_discretizate_bivdensity(SEXP densitySEXP, SEXP parametersSEXP, SEXP ini_point1SEXP, SEXP truncation_point1SEXP, SEXP max_deltat1SEXP, SEXP ini_point2SEXP, SEXP truncation_point2SEXP, SEXP max_deltat2SEXP, SEXP max_probabilitySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Function >::type density(densitySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type parameters(parametersSEXP);
    Rcpp::traits::input_parameter< double >::type ini_point1(ini_point1SEXP);
    Rcpp::traits::input_parameter< double >::type truncation_point1(truncation_point1SEXP);
    Rcpp::traits::input_parameter< double >::type max_deltat1(max_deltat1SEXP);
    Rcpp::traits::input_parameter< double >::type ini_point2(ini_point2SEXP);
    Rcpp::traits::input_parameter< double >::type truncation_point2(truncation_point2SEXP);
    Rcpp::traits::input_parameter< double >::type max_deltat2(max_deltat2SEXP);
    Rcpp::traits::input_parameter< double >::type max_probability(max_probabilitySEXP);
    rcpp_result_gen = Rcpp::wrap(discretizate_bivdensity(density, parameters, ini_point1, truncation_point1, max_deltat1, ini_point2, truncation_point2, max_deltat2, max_probability));
    return rcpp_result_gen;
END_RCPP
}
// inf_norm
double inf_norm(arma::mat A);
RcppExport SEXP _phfrailty_inf_norm(SEXP ASEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type A(ASEXP);
    rcpp_result_gen = Rcpp::wrap(inf_norm(A));
    return rcpp_result_gen;
END_RCPP
}
// matrix_exponential
arma::mat matrix_exponential(arma::mat A);
RcppExport SEXP _phfrailty_matrix_exponential(SEXP ASEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type A(ASEXP);
    rcpp_result_gen = Rcpp::wrap(matrix_exponential(A));
    return rcpp_result_gen;
END_RCPP
}
// matrix_power
arma::mat matrix_power(int n, arma::mat A);
RcppExport SEXP _phfrailty_matrix_power(SEXP nSEXP, SEXP ASEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type A(ASEXP);
    rcpp_result_gen = Rcpp::wrap(matrix_power(n, A));
    return rcpp_result_gen;
END_RCPP
}
// vector_of_matrices
void vector_of_matrices(std::vector<arma::mat>& the_vector, const arma::mat& S, int size_vec);
RcppExport SEXP _phfrailty_vector_of_matrices(SEXP the_vectorSEXP, SEXP SSEXP, SEXP size_vecSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<arma::mat>& >::type the_vector(the_vectorSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type S(SSEXP);
    Rcpp::traits::input_parameter< int >::type size_vec(size_vecSEXP);
    vector_of_matrices(the_vector, S, size_vec);
    return R_NilValue;
END_RCPP
}
// matrix_VanLoan
arma::mat matrix_VanLoan(const arma::mat& A1, const arma::mat& A2, const arma::mat& B1);
RcppExport SEXP _phfrailty_matrix_VanLoan(SEXP A1SEXP, SEXP A2SEXP, SEXP B1SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type A1(A1SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type A2(A2SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type B1(B1SEXP);
    rcpp_result_gen = Rcpp::wrap(matrix_VanLoan(A1, A2, B1));
    return rcpp_result_gen;
END_RCPP
}
// EMstep
void EMstep(arma::vec& alpha, arma::mat& S, const Rcpp::NumericVector& obs, const Rcpp::NumericVector& weight);
RcppExport SEXP _phfrailty_EMstep(SEXP alphaSEXP, SEXP SSEXP, SEXP obsSEXP, SEXP weightSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec& >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type S(SSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type obs(obsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type weight(weightSEXP);
    EMstep(alpha, S, obs, weight);
    return R_NilValue;
END_RCPP
}
// EMstep_bivph
void EMstep_bivph(arma::vec& alpha, arma::mat& S11, arma::mat& S12, arma::mat& S22, const Rcpp::NumericMatrix& obs, const Rcpp::NumericVector& weight);
RcppExport SEXP _phfrailty_EMstep_bivph(SEXP alphaSEXP, SEXP S11SEXP, SEXP S12SEXP, SEXP S22SEXP, SEXP obsSEXP, SEXP weightSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec& >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type S11(S11SEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type S12(S12SEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type S22(S22SEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type obs(obsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type weight(weightSEXP);
    EMstep_bivph(alpha, S11, S12, S22, obs, weight);
    return R_NilValue;
END_RCPP
}
// ph_density
Rcpp::NumericVector ph_density(Rcpp::NumericVector x, arma::vec alpha, arma::mat S);
RcppExport SEXP _phfrailty_ph_density(SEXP xSEXP, SEXP alphaSEXP, SEXP SSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type S(SSEXP);
    rcpp_result_gen = Rcpp::wrap(ph_density(x, alpha, S));
    return rcpp_result_gen;
END_RCPP
}
// ph_cdf
Rcpp::NumericVector ph_cdf(Rcpp::NumericVector x, arma::vec alpha, arma::mat S, bool lower_tail);
RcppExport SEXP _phfrailty_ph_cdf(SEXP xSEXP, SEXP alphaSEXP, SEXP SSEXP, SEXP lower_tailSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type S(SSEXP);
    Rcpp::traits::input_parameter< bool >::type lower_tail(lower_tailSEXP);
    rcpp_result_gen = Rcpp::wrap(ph_cdf(x, alpha, S, lower_tail));
    return rcpp_result_gen;
END_RCPP
}
// ph_laplace
Rcpp::NumericVector ph_laplace(Rcpp::NumericVector r, arma::vec alpha, arma::mat S);
RcppExport SEXP _phfrailty_ph_laplace(SEXP rSEXP, SEXP alphaSEXP, SEXP SSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type r(rSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type S(SSEXP);
    rcpp_result_gen = Rcpp::wrap(ph_laplace(r, alpha, S));
    return rcpp_result_gen;
END_RCPP
}
// ph_laplace_der_nocons
Rcpp::NumericVector ph_laplace_der_nocons(Rcpp::NumericVector r, int n, arma::vec alpha, arma::mat S);
RcppExport SEXP _phfrailty_ph_laplace_der_nocons(SEXP rSEXP, SEXP nSEXP, SEXP alphaSEXP, SEXP SSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type r(rSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type S(SSEXP);
    rcpp_result_gen = Rcpp::wrap(ph_laplace_der_nocons(r, n, alpha, S));
    return rcpp_result_gen;
END_RCPP
}
// bivph_density
Rcpp::NumericVector bivph_density(Rcpp::NumericMatrix x, arma::vec alpha, arma::mat S11, arma::mat S12, arma::mat S22);
RcppExport SEXP _phfrailty_bivph_density(SEXP xSEXP, SEXP alphaSEXP, SEXP S11SEXP, SEXP S12SEXP, SEXP S22SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type S11(S11SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type S12(S12SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type S22(S22SEXP);
    rcpp_result_gen = Rcpp::wrap(bivph_density(x, alpha, S11, S12, S22));
    return rcpp_result_gen;
END_RCPP
}
// bivph_tail
Rcpp::NumericVector bivph_tail(Rcpp::NumericMatrix x, arma::vec alpha, arma::mat S11, arma::mat S12, arma::mat S22);
RcppExport SEXP _phfrailty_bivph_tail(SEXP xSEXP, SEXP alphaSEXP, SEXP S11SEXP, SEXP S12SEXP, SEXP S22SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type S11(S11SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type S12(S12SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type S22(S22SEXP);
    rcpp_result_gen = Rcpp::wrap(bivph_tail(x, alpha, S11, S12, S22));
    return rcpp_result_gen;
END_RCPP
}
// bivph_laplace
Rcpp::NumericVector bivph_laplace(Rcpp::NumericMatrix r, arma::vec alpha, arma::mat S11, arma::mat S12, arma::mat S22);
RcppExport SEXP _phfrailty_bivph_laplace(SEXP rSEXP, SEXP alphaSEXP, SEXP S11SEXP, SEXP S12SEXP, SEXP S22SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type r(rSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type S11(S11SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type S12(S12SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type S22(S22SEXP);
    rcpp_result_gen = Rcpp::wrap(bivph_laplace(r, alpha, S11, S12, S22));
    return rcpp_result_gen;
END_RCPP
}
// bivph_laplace_der_nocons
Rcpp::NumericVector bivph_laplace_der_nocons(Rcpp::NumericMatrix r, int n, int m, arma::vec alpha, arma::mat S11, arma::mat S12, arma::mat S22);
RcppExport SEXP _phfrailty_bivph_laplace_der_nocons(SEXP rSEXP, SEXP nSEXP, SEXP mSEXP, SEXP alphaSEXP, SEXP S11SEXP, SEXP S12SEXP, SEXP S22SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type r(rSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type m(mSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type S11(S11SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type S12(S12SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type S22(S22SEXP);
    rcpp_result_gen = Rcpp::wrap(bivph_laplace_der_nocons(r, n, m, alpha, S11, S12, S22));
    return rcpp_result_gen;
END_RCPP
}
// embedded_mc
arma::mat embedded_mc(arma::mat S);
RcppExport SEXP _phfrailty_embedded_mc(SEXP SSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type S(SSEXP);
    rcpp_result_gen = Rcpp::wrap(embedded_mc(S));
    return rcpp_result_gen;
END_RCPP
}
// cumulate_matrix
arma::mat cumulate_matrix(arma::mat A);
RcppExport SEXP _phfrailty_cumulate_matrix(SEXP ASEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type A(ASEXP);
    rcpp_result_gen = Rcpp::wrap(cumulate_matrix(A));
    return rcpp_result_gen;
END_RCPP
}
// cumulate_vector
arma::vec cumulate_vector(arma::vec A);
RcppExport SEXP _phfrailty_cumulate_vector(SEXP ASEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type A(ASEXP);
    rcpp_result_gen = Rcpp::wrap(cumulate_vector(A));
    return rcpp_result_gen;
END_RCPP
}
// initial_state
long initial_state(arma::vec cum_alpha, double u);
RcppExport SEXP _phfrailty_initial_state(SEXP cum_alphaSEXP, SEXP uSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type cum_alpha(cum_alphaSEXP);
    Rcpp::traits::input_parameter< double >::type u(uSEXP);
    rcpp_result_gen = Rcpp::wrap(initial_state(cum_alpha, u));
    return rcpp_result_gen;
END_RCPP
}
// new_state
long new_state(long prev_state, arma::mat cum_embedded_mc, double u);
RcppExport SEXP _phfrailty_new_state(SEXP prev_stateSEXP, SEXP cum_embedded_mcSEXP, SEXP uSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< long >::type prev_state(prev_stateSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type cum_embedded_mc(cum_embedded_mcSEXP);
    Rcpp::traits::input_parameter< double >::type u(uSEXP);
    rcpp_result_gen = Rcpp::wrap(new_state(prev_state, cum_embedded_mc, u));
    return rcpp_result_gen;
END_RCPP
}
// rphasetype
Rcpp::NumericVector rphasetype(int n, arma::vec alpha, arma::mat S);
RcppExport SEXP _phfrailty_rphasetype(SEXP nSEXP, SEXP alphaSEXP, SEXP SSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type S(SSEXP);
    rcpp_result_gen = Rcpp::wrap(rphasetype(n, alpha, S));
    return rcpp_result_gen;
END_RCPP
}
// clone_vector
NumericVector clone_vector(NumericVector v);
RcppExport SEXP _phfrailty_clone_vector(SEXP vSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type v(vSEXP);
    rcpp_result_gen = Rcpp::wrap(clone_vector(v));
    return rcpp_result_gen;
END_RCPP
}
// clone_matrix
NumericMatrix clone_matrix(NumericMatrix m);
RcppExport SEXP _phfrailty_clone_matrix(SEXP mSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type m(mSEXP);
    rcpp_result_gen = Rcpp::wrap(clone_matrix(m));
    return rcpp_result_gen;
END_RCPP
}
// random_structure
List random_structure(int p, String structure, double scale_factor);
RcppExport SEXP _phfrailty_random_structure(SEXP pSEXP, SEXP structureSEXP, SEXP scale_factorSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< String >::type structure(structureSEXP);
    Rcpp::traits::input_parameter< double >::type scale_factor(scale_factorSEXP);
    rcpp_result_gen = Rcpp::wrap(random_structure(p, structure, scale_factor));
    return rcpp_result_gen;
END_RCPP
}
// random_structure_bivph
List random_structure_bivph(int p1, int p2, double scale_factor);
RcppExport SEXP _phfrailty_random_structure_bivph(SEXP p1SEXP, SEXP p2SEXP, SEXP scale_factorSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type p1(p1SEXP);
    Rcpp::traits::input_parameter< int >::type p2(p2SEXP);
    Rcpp::traits::input_parameter< double >::type scale_factor(scale_factorSEXP);
    rcpp_result_gen = Rcpp::wrap(random_structure_bivph(p1, p2, scale_factor));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_phfrailty_discretizate_density", (DL_FUNC) &_phfrailty_discretizate_density, 6},
    {"_phfrailty_discretizate_bivdensity", (DL_FUNC) &_phfrailty_discretizate_bivdensity, 9},
    {"_phfrailty_inf_norm", (DL_FUNC) &_phfrailty_inf_norm, 1},
    {"_phfrailty_matrix_exponential", (DL_FUNC) &_phfrailty_matrix_exponential, 1},
    {"_phfrailty_matrix_power", (DL_FUNC) &_phfrailty_matrix_power, 2},
    {"_phfrailty_vector_of_matrices", (DL_FUNC) &_phfrailty_vector_of_matrices, 3},
    {"_phfrailty_matrix_VanLoan", (DL_FUNC) &_phfrailty_matrix_VanLoan, 3},
    {"_phfrailty_EMstep", (DL_FUNC) &_phfrailty_EMstep, 4},
    {"_phfrailty_EMstep_bivph", (DL_FUNC) &_phfrailty_EMstep_bivph, 6},
    {"_phfrailty_ph_density", (DL_FUNC) &_phfrailty_ph_density, 3},
    {"_phfrailty_ph_cdf", (DL_FUNC) &_phfrailty_ph_cdf, 4},
    {"_phfrailty_ph_laplace", (DL_FUNC) &_phfrailty_ph_laplace, 3},
    {"_phfrailty_ph_laplace_der_nocons", (DL_FUNC) &_phfrailty_ph_laplace_der_nocons, 4},
    {"_phfrailty_bivph_density", (DL_FUNC) &_phfrailty_bivph_density, 5},
    {"_phfrailty_bivph_tail", (DL_FUNC) &_phfrailty_bivph_tail, 5},
    {"_phfrailty_bivph_laplace", (DL_FUNC) &_phfrailty_bivph_laplace, 5},
    {"_phfrailty_bivph_laplace_der_nocons", (DL_FUNC) &_phfrailty_bivph_laplace_der_nocons, 7},
    {"_phfrailty_embedded_mc", (DL_FUNC) &_phfrailty_embedded_mc, 1},
    {"_phfrailty_cumulate_matrix", (DL_FUNC) &_phfrailty_cumulate_matrix, 1},
    {"_phfrailty_cumulate_vector", (DL_FUNC) &_phfrailty_cumulate_vector, 1},
    {"_phfrailty_initial_state", (DL_FUNC) &_phfrailty_initial_state, 2},
    {"_phfrailty_new_state", (DL_FUNC) &_phfrailty_new_state, 3},
    {"_phfrailty_rphasetype", (DL_FUNC) &_phfrailty_rphasetype, 3},
    {"_phfrailty_clone_vector", (DL_FUNC) &_phfrailty_clone_vector, 1},
    {"_phfrailty_clone_matrix", (DL_FUNC) &_phfrailty_clone_matrix, 1},
    {"_phfrailty_random_structure", (DL_FUNC) &_phfrailty_random_structure, 3},
    {"_phfrailty_random_structure_bivph", (DL_FUNC) &_phfrailty_random_structure_bivph, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_phfrailty(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
