# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' L_inf norm of a matrix
#'
#' Computes the inf norm of a matrix A, defined as
#' L-oo A =  max ( 1 <= I <= M ) sum ( 1 <= J <= N ) abs ( A(I,J) ).
#' @param A a matrix
#' @return The norm
#'
inf_norm <- function(A) {
    .Call(`_phfrailty_inf_norm`, A)
}

#' Matrix exponential algorithm
#'
#' MATLAB's built-in algorithm - Pade approximation
#' @param A a matrix
#'
matrix_exponential <- function(A) {
    .Call(`_phfrailty_matrix_exponential`, A)
}

#' Phase-type density
#'
#' Computes the density of a phase-type distribution with parameters \code{alpha} and \code{S} at \code{x}
#' @param x non-negative value
#' @param alpha vector of initial probabilities
#' @param S sub-intensity matrix
#' @return The density at \code{x}
#'
ph_density <- function(x, alpha, S) {
    .Call(`_phfrailty_ph_density`, x, alpha, S)
}

