# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' L_inf norm of a matrix
#'
#' Computes the inf norm of a matrix A, defined as
#' L-oo A =  max ( 1 <= I <= M ) sum ( 1 <= J <= N ) abs ( A(I,J) ).
#' @param A a matrix
#' @return The norm
#'
inf_norm <- function(A) {
    .Call(`_phfrailty_inf_norm`, A)
}

#' Matrix exponential algorithm
#'
#' MATLAB's built-in algorithm - Pade approximation
#' @param A a matrix
#'
matrix_exponential <- function(A) {
    .Call(`_phfrailty_matrix_exponential`, A)
}

